swagger: '2.0'
info:
  $ref: ./info/index.yml
host: hub.subut.ai
schemes:
  - https
basePath: /rest/v1/client
produces:
  - application/json
paths:
  $ref: ./paths/index.yml
definitions:
  $ref: ./definitions/index.yml